# Generated by Django 6.0.6 on 2026-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(verbose_name=255)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(upload_to='haqida/')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(verbose_name=255)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sharhi', models.TextField()),
                ('rasm', models.ImageField(upload_to='mahsulot/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kichik_sarlavha', models.CharField(max_length=255)),
                ('katta_sarlavha', models.CharField(max_length=255)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(upload_to='reklama/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(verbose_name=150)),
                ('kasbi', models.CharField(verbose_name=50)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(upload_to='users/')),
            ],
        ),
    ]
