# Generated by Django 6.0.6 on 2026-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yordamchi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='reklama',
            name='katta_sarlavha',
        ),
        migrations.AlterField(
            model_name='product',
            name='nomi',
            field=models.CharField(verbose_name=255),
        ),
    ]
